apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamutkart-d
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gamutkart-c
  template:
    metadata:
      labels:
        name: gamutkart-c
    spec:
      containers:
      - name: gamutkart-c
        image: jaddusantoshkumar/gamutkart:18
        ports:
        - containerPort: 8080
